###############################################################################
# User's configuration file for the ESMValTool
###############################################################################
---

# Rootpaths to the data from different projects (lists are also possible)
rootpath:
#  CMIP3: /work/bd0854/DATA/ESMValTool2/CMIP3/
  CMIP5: [/work/kd0956/CMIP5/data/cmip5/output1]
  CMIP6: [/work/ik1017/CMIP6/data/CMIP6/]
  DAMIP: [/work/ik1017/CMIP6/data/DAMIP/]
  OBS: [/work/bd0854/DATA/ESMValTool2/OBS, /work/bd0854/b380971/output/revision/data_formatting_20230112_110337]
#  OBS6: [/work/bd0854/b309137/data_ext/, /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS]
#  obs4MIPs: [/work/bd0854/b309137/data_ext/, /mnt/lustre02/work/bd0854/DATA/ESMValTool2/OBS]
#  ana4mips: ~/ana4mips_inputpath
#  native6:  ~/native6_inputpath
  RAWOBS: /work/bd0854/b380971/data_temp/raw_obs/Tier2/HadISST #/work/bd0854/DATA/ESMValTool2/OBS
  default: /work/bd0854/DATA/ESMValTool2/OBS
  native6: [/work/bd0854/DATA/ESMValTool2/RAWOBS, /work/bd0854/b380971/data_temp/CDS/]

# Directory structure for input data: [default]/BADC/DKRZ/ETHZ/etc
# See config-developer.yml for definitions.
drs:
  CMIP3: DKRZ
  CMIP5: DKRZ
  CMIP6: DKRZ

# Directory tree created by automatically downloading from ESGF
#rootpath:
#  CMIP3: ~/climate_data
#  CMIP5: ~/climate_data
#  CMIP6: /work/bd0854/b380971/data_temp/automatic_download
#  CORDEX: ~/climate_data
#  obs4MIPs: ~/climate_data
#drs:
#  CMIP3: ESGF
#  CMIP5: ESGF
#  CMIP6: ESGF
#  CORDEX: ESGF
#  obs4MIPs: ESGF

# Run at most this many tasks in parallel [null]/1/2/3/4/..
# Set to null to use the number of available CPUs.
# If you run out of memory, try setting max_parallel_tasks to 1 and check the
# amount of memory you need for that by inspecting the file
# run/resource_usage.txt in the output directory. Using the number there you
# can increase the number of parallel tasks again to a reasonable number for
# the amount of memory available in your system.
max_parallel_tasks: null

# Destination directory
output_dir: /work/bd0854/b380971/output/revision/

# Directory for storing downloaded climate data
download_dir: /work/bd0854/b380971/data_temp/CMIP6

# Auxiliary data directory (used for some additional datasets)
auxiliary_data_dir: ./auxiliary_data

# Set the console log level debug, [info], warning, error
log_level: info

# Disable the automatic download of missing CMIP3, CMIP5, CMIP6, CORDEX,
# and obs4MIPs data from ESGF by default. This is useful if you are working
# on a computer without an internet connection.
offline: true
# Exit on warning (only for NCL diagnostic scripts)? true/[false]
exit_on_warning: false
# Plot file format? [png]/pdf/ps/eps/epsi
output_file_type: png
# Use netCDF compression true/[false]
compress_netcdf: false
# Save intermediary cubes in the preprocessor true/[false]
save_intermediary_cubes: false
# Remove the preproc dir if all fine
remove_preproc_dir: false
# Path to custom config-developer file, to customise project configurations.
# See config-developer.yml for an example. Set to None to use the default
# config_developer_file: null
# Get profiling information for diagnostics
# Only available for Python diagnostics
profile_diagnostic: true
