###############################################################################
# Developer's configuration file for the ESMValTool
###############################################################################
# This file retains the project- and machine-dependent directory and file name
# definitions of the input and output data
# Each dictionary is structured as follows
#
# PROJECT:
#   input_dir:
#     default:
#     drs1:
#     drs2:
#     etc:
#   input_file:
#   output_file:
#
# Only the default drs is mandatory, the others are optional
###############################################################################

CMIP5:
  input_dir:
    default: '/'
    BSC: '[institute]/[model]/[exp]/S[startdate]/[freq]/[realm]/[var]/[ensemble]'
    BADC: '[institute]/[model]/[exp]/[freq]/[realm]/[mip]/[ensemble]/latest/[var]'
    DKRZ: '[institute]/[model]/[exp]/[realm]/[freq]/[mip]/[ensemble]/[latestversion]/[var]'
    ETHZ: '[exp]/[mip]/[var]/[model]/[ensemble]/'
    SMHI: '[model]/[ensemble]/[exp]/[freq]'
  input_file: '[var]_[mip]_[model]_[exp]_*[ensemble]_*'
  output_file: '[model]_[mip]_[exp]_[ensemble]_[field]_[var]_[start_year]-[end_year]'

SPECS:
  input_dir: '[institute]/[model]/[exp]/S[startdate]/[freq]/[realm]/[var]/[ensemble]'
  input_file:
    default: '[var]_[mip]_[model]_[exp]_S[startdate]_[ensemble]_*'
  output_file: '[model]_[mip]_[exp]_[ensemble]_[field]_[var]_[start_year]-[end_year]'

OBS:
  input_dir:
    default: '[tier]/[model]'
  input_file: '[project]_[model]_[type]_[version]_[field]_[var]_*'
  output_file: '[project]_[model]_[type]_[version]_[field]_[var]_[start_year]-[end_year]'

obs4mips:
  input_dir:
    default: '[tier]/[model]'
  input_file: '[var]_[model]_[level]_[version]_*'
  output_file: '[project]_[model]_[level]_[version]_[field]_[var]_[start_year]-[end_year]'

ana4mips:
  input_dir:
    default: '[tier]/[model]'
  input_file: '[var]_[mip]_[type]_[model]_*'
  output_file: '[project]_[mip]_[type]_[model]_[field]_[var]_[start_year]-[end_year]'

CCMVal1:
  input_dir:
    default: '[exp]/[model]'
  input_file: '[project]_[exp]_[name]_[ensemble]_[field]_[var]'
  output_file: '[project]_[exp]_[name]_[ensemble]_[field]_[var]_[start_year]-[end_year]'

CCMVal2:
  input_dir:
    default: '[exp]/[model]'
  input_file: '[project]_[exp]_[name]_[ensemble]_[field]_[var]'
  output_file: '[project]_[exp]_[name]_[ensemble]_[field]_[var]_[start_year]-[end_year]'

EMAC:
  input_dir:
    default: '[model]'
  input_file: ''
  output_file: '[model]_[ensemble]_[field]_[var]_[start_year]-[end_year]'
