name: Install from Source

# runs on a push on main and at the end of every day
on:
  push:
    branches:
    - main
    - test-fix
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: True
          mamba-version: "*"
          activate-environment: esmvaltool
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
          channel-priority: true
      - shell: bash -l {0}
        run: mkdir -p source_install_linux_artifacts_python_${{ matrix.python-version }}
      - shell: bash -l {0}
        run: conda --version 2>&1 | tee source_install_linux_artifacts_python_${{ matrix.python-version }}/conda_version.txt
      - shell: bash -l {0}
        run: python -V 2>&1 | tee source_install_linux_artifacts_python_${{ matrix.python-version }}/python_version.txt
      - shell: bash -l {0}
        run: pip install -e .[develop] 2>&1 | tee source_install_linux_artifacts_python_${{ matrix.python-version }}/install.txt
      - shell: bash -l {0}
        run: esmvaltool --help
      - shell: bash -l {0}
        run: esmvaltool version 2>&1 | tee source_install_linux_artifacts_python_${{ matrix.python-version }}/version.txt
      - name: Upload artifacts
        if: ${{ always() }}  # upload artifacts even if fail
        uses: actions/upload-artifact@v2
        with:
          name: Source_Install_Linux_python_${{ matrix.python-version }}
          path: source_install_linux_artifacts_python_${{ matrix.python-version }}

# uncomment from here when we have a testing environment on an OSX machine
# and we know that this should work
#
#  osx:
#    runs-on: "macos-latest"
#    strategy:
#      matrix:
#        python-version: [3.7, 3.8, 3.9]
#      fail-fast: false
#    name: OSX Python ${{ matrix.python-version }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          activate-environment: esmvaltool
#          environment-file: environment.yml
#          python-version: ${{ matrix.python-version }}
#          miniconda-version: "latest"
#          channels: conda-forge
#      - shell: bash -l {0}
#        run: mkdir -p source_install_osx_artifacts_python_${{ matrix.python-version }}
#      - shell: bash -l {0}
#        run: conda --version 2>&1 | tee source_install_osx_artifacts_python_${{ matrix.python-version }}/conda_version.txt
#      - shell: bash -l {0}
#        run: python -V 2>&1 | tee source_install_osx_artifacts_python_${{ matrix.python-version }}/python_version.txt
#      - shell: bash -l {0}
#        run: pip install -e .[develop] 2>&1 | tee source_install_osx_artifacts_python_${{ matrix.python-version }}/install.txt
#      - shell: bash -l {0}
#        run: esmvaltool --help
#      - shell: bash -l {0}
#        run: esmvaltool version 2>&1 | tee source_install_osx_artifacts_python_${{ matrix.python-version }}/version.txt
#      - name: Upload artifacts
#        if: ${{ always() }}  # upload artifacts even if fail
#        uses: actions/upload-artifact@v2
#        with:
#          name: Source_Install_OSX_python_${{ matrix.python-version }}
#          path: source_install_osx_artifacts_python_${{ matrix.python-version }}
